partial implementation for keepass object + mypy (#33)
also try to add mypy

Co-authored-by: Klaus Foerster <klaus.foerster@mhcomm.fr>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,7 @@ jobs:
           run: |
             python -m pip install -U pip
             python -m pip install flake8
+            python -m pip install mypy
         # Uncomment as soon as import order is cleaned
         # - name: check import order
         #   if: ${{ matrix.python-version == '3.8' }}
@@ -34,6 +35,14 @@ jobs:
           if: ${{ matrix.python-version < 'pypy' }}
           run: |
             python -m flake8 mytb
+        - name: mypy
+          if: ${{ matrix.python-version < 'pypy' }}
+          run: |
+            pip install -r requirements/types.txt
+            mypy mytb | tee mypy.txt || true
+            error_count=$(grep -c 'error:' mypy.txt)
+            echo "Got $error_count mypy errors"
+            [[ $error_count -le 21 ]]
         - name: pytest
           run: |
             python -m pip install -r requirements/all.txt
